-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.role_user DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.role_user DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.lesson DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.homework DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.course_user DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.course_user DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.lesson_files DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.lesson_files DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.feedback_response DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.feedback_response DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.homework_response DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.homework_response DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public."user";

CREATE TABLE IF NOT EXISTS public."user"
(
    id uuid NOT NULL,
    name character varying NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL,
    telegram character varying,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.course;

CREATE TABLE IF NOT EXISTS public.course
(
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.role;

CREATE TABLE IF NOT EXISTS public.role
(
    id smallint NOT NULL,
    name character varying,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.role_user;

CREATE TABLE IF NOT EXISTS public.role_user
(
    user_id uuid,
    role_id smallint,
    PRIMARY KEY (user_id, role_id)
);

DROP TABLE IF EXISTS public.lesson;

CREATE TABLE IF NOT EXISTS public.lesson
(
    id uuid NOT NULL,
    name character varying,
    description character varying,
    scheduled_date date,
    "time" time with time zone,
    feedback_form json,
    course_id integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.homework;

CREATE TABLE IF NOT EXISTS public.homework
(
    "Id" uuid,
    task text NOT NULL,
    deadline date NOT NULL,
    form json,
    course_id integer NOT NULL,
    PRIMARY KEY ("Id")
);

DROP TABLE IF EXISTS public.course_user;

CREATE TABLE IF NOT EXISTS public.course_user
(
    user_id uuid,
    course_id integer,
    PRIMARY KEY (user_id, course_id)
);

DROP TABLE IF EXISTS public.files;

CREATE TABLE IF NOT EXISTS public.files
(
    id uuid NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.lesson_files;

CREATE TABLE IF NOT EXISTS public.lesson_files
(
    lesson_id uuid,
    file_id uuid,
    PRIMARY KEY (lesson_id, file_id)
);

DROP TABLE IF EXISTS public.feedback_response;

CREATE TABLE IF NOT EXISTS public.feedback_response
(
    id integer NOT NULL,
    user_id uuid NOT NULL,
    lession_id uuid NOT NULL,
    response json NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.homework_response;

CREATE TABLE IF NOT EXISTS public.homework_response
(
    id integer NOT NULL,
    user_id uuid NOT NULL,
    homework_id uuid NOT NULL,
    response json NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.role_user
    ADD FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.role_user
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson
    ADD FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.homework
    ADD FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course_user
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course_user
    ADD FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson_files
    ADD FOREIGN KEY (file_id)
    REFERENCES public.files (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lesson_files
    ADD FOREIGN KEY (lesson_id)
    REFERENCES public.lesson (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.feedback_response
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.feedback_response
    ADD FOREIGN KEY (lession_id)
    REFERENCES public.lesson (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.homework_response
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.homework_response
    ADD FOREIGN KEY (homework_id)
    REFERENCES public.homework ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;